### ISSUE TITLE
Collect routes not working

### ISSUE THREAD

**Issue by justinlaskowski** [tjmisko/sspi-data-collection#194]
Error message attached. Same issue for multiple different collect routes, I have pulled most recent changes
![Screenshot (58)](https://github.com/tjmisko/sspi-data-collection/assets/124819505/e3b7a097-1a88-4ead-8b7a-dc31d2243033)

**Comment by tjmisko** [comment]
The error is being thrown by a validator, which I implemented a few weeks ago. It's designed to catch errors in the format of raw observations. In this case, the validator is telling you that "'Raw' must be a string, dict, int, float, or list." Check the type of "Raw" that we're sending into raw_insert_one.
